import {
  AttributeType,
  ModifierType,
} from '@shared/engine/battle-v5/core/types';
import type { SectDefinitionWithoutPaths } from '../../core';
import { JIUJIE_CALAMITY, JIUJIE_SECT_ID } from './ids';

const effects = { damage: 0.14, heal: 0.12, shield: 0.14, status: 0.2 };
const durationMilestones = [
  { level: 60, bonus: 1 },
  { level: 120, bonus: 2 },
];

export const JIUJIE_BASE_DEFINITION: SectDefinitionWithoutPaths = {
  id: JIUJIE_SECT_ID,
  name: '掌灯司',
  description:
    '朝廷机构，登记、编号、镇压诡异。司中照灯记行，以不可驱散的灯痕标记诡异，待结案之日一并清算。',
  raceIds: ['human'],
  configVersion: 1,
  foundationPassiveId: 'jiujie-tianwei-runtime',
  combatResource: { id: JIUJIE_CALAMITY, name: '灯焰', icon: '🏮', max: 3 },
  methods: [
    {
      id: 'jiujie-canon',
      slot: 1,
      name: '《守灯律》',
      isPrimary: true,
      description: '掌灯司内库所执正法，总录照灯、记行、结案三法度。',
      growthProfile: { curve: 'balanced', effects, durationMilestones },
    },
    {
      id: 'calamity-eye',
      slot: 2,
      name: '《灯眼观行》',
      description: '以身为灯眼，观来者之行而承其灾。',
      growthProfile: {
        curve: 'early',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAX_HP,
          type: ModifierType.ADD,
          maxValue: 0.12,
        },
      },
    },
    {
      id: 'heavenly-record',
      slot: 3,
      name: '《案簿》',
      description: '以灯听辨行为，以案簿记其主罪。',
      growthProfile: {
        curve: 'early',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAGIC_ATK,
          type: ModifierType.ADD,
          maxValue: 0.15,
        },
      },
    },
    {
      id: 'thunder-prison',
      slot: 4,
      name: '《灯牢镇影》',
      description: '灯牢穿透护持，使灯焰不为法障所蔽。',
      growthProfile: {
        curve: 'balanced',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAGIC_PENETRATION,
          type: ModifierType.FIXED,
          maxValue: 0.08,
        },
      },
    },
    {
      id: 'cause-judgment',
      slot: 5,
      name: '《结案问灯》',
      description: '问灯下因果、收案债，留足清算之焰。',
      growthProfile: {
        curve: 'balanced',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAX_MP,
          type: ModifierType.ADD,
          maxValue: 0.18,
        },
      },
    },
    {
      id: 'crossing-calamity',
      slot: 6,
      name: '《渡渊守身》',
      description: '渡渊之后仍守法身，不以灯焰伤己。',
      growthProfile: {
        curve: 'early',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAGIC_DEF,
          type: ModifierType.ADD,
          maxValue: 0.14,
        },
      },
    },
  ],
  abilities: [
    {
      id: 'thunder-finger',
      kind: 'default',
      baseName: '照灯指',
      description: '仅在主动神通均不可用时使用，以灯焰造成基础伤害。',
      role: 'generator',
      unlock: { type: 'method', methodId: 'jiujie-canon', level: 1 },
      mpCost: 0,
      cooldown: 0,
    },
    {
      id: 'heaven-hearing',
      kind: 'active',
      baseName: '灯听引焰',
      description: '造成0.55倍法攻灯焰伤害，并在目标身上留下不可驱散的灯痕。',
      role: 'generator',
      unlock: { type: 'method', methodId: 'jiujie-canon', level: 1 },
      mpCost: 80,
      cooldown: 0,
    },
    {
      id: 'receive-calamity',
      kind: 'active',
      baseName: '承灯受焰',
      description: '暂承来力，将受过的灾厄记入灯眼。',
      role: 'defensive',
      unlock: { type: 'method', methodId: 'calamity-eye', level: 1 },
      mpCost: 120,
      cooldown: 4,
    },
    {
      id: 'calamity-seal',
      kind: 'active',
      baseName: '案簿落印',
      description: '造成0.25倍法攻灯焰伤害并落印；目标已有灯痕时，额外增加一层案债。',
      role: 'generator',
      unlock: { type: 'method', methodId: 'heavenly-record', level: 1 },
      mpCost: 120,
      cooldown: 2,
    },
    {
      id: 'thunder-prison-question',
      kind: 'active',
      baseName: '灯牢问行',
      description: '造成0.65倍法攻灯焰伤害，追问目标仍在案中的下一步并推进结案。',
      role: 'combo',
      unlock: { type: 'method', methodId: 'thunder-prison', level: 1 },
      mpCost: 140,
      cooldown: 2,
    },
    {
      id: 'borrow-calamity',
      kind: 'active',
      baseName: '借焰护身',
      description: '消耗一分灯焰，获得相当于最大气血15%的护盾。',
      role: 'defensive',
      unlock: { type: 'method', methodId: 'crossing-calamity', level: 1 },
      mpCost: 100,
      cooldown: 3,
    },
    {
      id: 'causal-echo',
      kind: 'active',
      baseName: '灯影回响',
      description: '造成0.45倍法攻的基础灯焰伤害，并根据案债追加伤害。',
      role: 'utility',
      unlock: { type: 'method', methodId: 'cause-judgment', level: 5 },
      mpCost: 140,
      cooldown: 3,
    },
    {
      id: 'nine-sky-settlement',
      kind: 'active',
      baseName: '九灯清算',
      description: '以灯焰为引，清算目标累积的案债。',
      role: 'finisher',
      unlock: { type: 'method', methodId: 'jiujie-canon', level: 10 },
      mpCost: 200,
      cooldown: 5,
    },
    {
      id: 'jiujie-tianwei-runtime',
      kind: 'passive',
      baseName: '灯律裁决',
      description:
        '掌灯司弟子受到敌方主动灯律或负面技能时，有20%的几率免疫整个技能。',
      role: 'defensive',
      unlock: { type: 'always' },
      sourceMethodId: 'heavenly-record',
    },
    {
      id: 'jiujie-law-runtime',
      kind: 'passive',
      baseName: '灯律运行',
      description: '记录灯痕触发与司中案簿。',
      role: 'utility',
      unlock: { type: 'always' },
      sourceMethodId: 'jiujie-canon',
      visibility: 'internal',
    },
  ],
  onboarding: {
    initialContribution: 30,
    initialMethods: {
      'jiujie-canon': 5,
      'calamity-eye': 1,
      'heavenly-record': 1,
      'thunder-prison': 1,
      'cause-judgment': 1,
      'crossing-calamity': 1,
    },
    initialAbilityLoadout: ['heaven-hearing', 'calamity-seal', null, null],
  },
};
