import type { SectMapHotspot, SectPresentationTheme } from '../../core';
import { JIUJIE_SECT_ID } from './ids';
const h = (id: string, label: string, left: string, top: string, route: string, permission: SectMapHotspot['permission'], note: string, facility?: string, locked?: boolean, visitor?: SectMapHotspot['visitor']): SectMapHotspot => ({ id, label, left, top, route, permission, note, facility, locked, visitor });
export const JIUJIE_SECT_PRESENTATION: SectPresentationTheme = {
  sectId: JIUJIE_SECT_ID,
  announcement: '今夜京畿第三更过后，西市有野腌出没，已编号存档。签押人夜间行经坊门，须先照灯，再入街巷。',
  visual: {
    sigilLabel: '灯楼九曜',
    sigilGlyph: '灯',
    palette: ['#1a1713', '#7a3b2e', '#d8a03a'],
    motto: '灯焰不散，夜有所归。',
    motif: '九盏灯悬于京畿雾中，为一城夜路标定归途。',
  },
  onboarding: {
    summary: '掌灯司登记、编号、镇压诡异。以身照灯，或以功勋定罪；待诡异归于档案，再作最后结案。',
    traits: ['照灯记行', '灯焰不散', '承功定罪'],
    script: {
      id: 'jiujie-onboarding', title: '照灯听夜', theme: 'steel',
      backdrop: { src: '/assets/sect/onboarding/jiujie.webp', alt: '掌灯司司务堂前，新签押人接受录事验名，远处灯楼悬于京畿雾中' },
      acts: [
        { id: 'ascend-heaven-stair', title: '登门有籍', scene: '掌灯司 · 司务堂', body: '你沿着京畿长街行至司务堂前。门内没有迎客钟，也没有引路小吏。只有堂上灯楼之间，一盏盏灯焰按着相同的间隔亮起，像有人正在为满城灯火校准一盏看不见的灯。', speaker: '守门吏：“司中不问来者从何处来。签下这卷案，便要让灯焰知道你将如何行事。”', backgroundPosition: '50% 46%', tone: 'mist' },
        { id: 'thunder-pool-verdict', title: '照灯验名', scene: '掌灯司 · 灯楼', body: '灯楼中央立着一方空白档案。录事将你的姓名写上去，墨迹尚未干透，灯焰便从楼顶垂落。火光没有烧毁档案，只在纸面留下第一道细密的灯痕。', speaker: '录事：“灯焰不替你行事。它只记下你已经做过的事。”', backgroundPosition: '50% 60%', tone: 'steel' },
        { id: 'calamity-eye', title: '灯焰临身', scene: '掌灯司 · 巡灯处', body: '左侧巡灯处的阵纹忽然亮起。灯焰落在你的身上，并未立刻熄灭，而是沿着衣袍与灯脉留下的灯痕缓缓回流。你感受到的不是一记照看，而是一场尚未结束的夜。', speaker: '巡灯吏：“若以自身为灯眼，便要先学会照看。来物经过你，才知道该归向何处。”', backgroundPosition: '24% 48%', tone: 'ember' },
        { id: 'heavenly-condemnation', title: '功勋加身', scene: '掌灯司 · 缉诡司', body: '右侧缉诡司内，数枚卷宗依次浮起。有人挥掌，卷宗记下击杀；有人施术护持，卷宗记下支援；有人试图封住来路，卷宗便留下处置的判印。相同的灯痕再次出现时，第二道墨色判印随之落下。', speaker: '缉诡吏：“司中不禁你出手。只是同一条路若再走一次，便不能说自己不知它通向何处。”', backgroundPosition: '76% 48%', tone: 'steel' },
        { id: 'nine-gates-entry', title: '灯位入司', scene: '掌灯司 · 灯位', body: '你回到灯楼中央。档案上的灯痕已经不再空白：有的沿着你的身躯回流，有的沉入缉诡司的卷宗。九座灯位同时亮起，却只开启了你脚下的那一重。', speaker: '楼中：“我不求无夜，只求夜有所归。今日入司，先照一灯。”', backgroundPosition: '50% 38%', tone: 'mist' },
      ],
    },
  },
  map: {
    image: '/assets/sect/jiujie-map.webp',
    alt: '掌灯司京畿舆图，中央灯楼连接司务堂、巡灯处、缉诡司与悬空灯位。',
    aspectRatio: 1536 / 1024,
    hotspots: [
      h('hall', '灯楼', '50%', '50%', '/game/sect/hall', 'sect.hall.view', '身份 · 同门 · 周俸'),
      h('archive', '档案库', '50%', '8%', '/game/sect/archive', 'sect.archive.use', '功法研习', 'archive'),
      h('cliff', '巡灯处', '17%', '31%', '/game/sect/enlightenment-cliff', 'sect.enlightenment.use', '灯焰临身 · 流派参悟'),
      h('condemnation', '缉诡司', '82%', '31%', '/game/sect/enlightenment-cliff', 'sect.enlightenment.use', '功勋加身 · 流派参悟'),
      h('affairs', '司务堂', '50%', '71%', '/game/sect/affairs', 'sect.tasks.use', '日常 · 周常 · 晋升'),
      h('arena', '灯台演武场', '50%', '28%', '/game/sect/arena', 'sect.arena.use', '神通 · 战术 · 小比'),
      h('treasury', '请物簿', '74%', '42%', '/game/sect/treasury', 'sect.shop.use', '功勋兑换'),
      h('industries', '营造司', '82%', '73%', '/game/sect/industries', 'sect.construction.view', '设施建设 · 灯油券捐献'),
      h('cultivation', '守灯静室', '38%', '14%', '/game/sect/cultivation-room', 'sect.facility.cultivation.use', '闭关窥悟 · 设施灯效', 'cultivation_room'),
      h('alchemy', '闻香房', '67%', '14%', '/game/sect/alchemy', 'sect.facility.alchemy.use', '制香 · 设施灯效', 'workshop'),
      h('refinery', '封灵坊', '89%', '48%', '/game/sect/refinery', 'sect.facility.refinery.use', '封灵 · 设施灯效', 'workshop'),
      h('vein', '灯油井', '17%', '67%', '/game/sect/spirit-vein', 'sect.spirit_vein.view', '井场巡视 · 灯油券收益 · 采油', 'spirit_vein'),
      h('garden', '灯下草圃', '9%', '80%', '/game/sect/herb-garden', 'sect.herb_garden.view', '草木长势 · 产出待开放', 'herb_garden'),
      h('gate', '灯位门', '50%', '88%', '/game/sect/gate', 'sect.gate.view', '门禁动态 · 清扫差事', undefined, undefined, { description: '灯位门尚未全开，外客只能在门外递交拜帖。' }),
      h('cave', '灯隐居', '29%', '79%', '/game/sect/cave', 'sect.cave.view', '签押人居所'),
      { id: 'formation', label: '护城灯阵', left: '61%', top: '23%', permission: 'sect.formation.view', note: '宗门战后续开放', facility: 'formation', locked: true, visitor: { description: '护城灯阵尚未全开，外客只能在长街尽头看见灯焰。' } },
    ],
  },
  facilityLabels: { archive: '档案库', cultivation_room: '守灯静室', workshop: '封灵坊', alchemy: '闻香房', refinery: '封灵坊', spirit_vein: '灯油井', herb_garden: '灯下草圃', formation: '护城灯阵' },
  lockedFacilities: ['formation'],
  rooms: {
    affairs: { actors: { daily: { id: 'jiujie-daily', name: '照灯执事', greeting: '今日灯焰平稳，日常委托可依档案次序领取。' }, weekly: { id: 'jiujie-weekly', name: '守簿翁', greeting: '周常卷宗已按灯痕归档，想查哪一卷？' }, promotion: { id: 'jiujie-promotion', name: '掌灯大人', greeting: '晋升之前，先问你是否敢直面自己点过的灯。' } } },
    hall: { actors: { registry: { id: 'jiujie-registry', name: '录事', greeting: '身份与名册均已照灯登记。' }, stipend: { id: 'jiujie-stipend', name: '发俸', greeting: '周俸按灯楼规矩发放。' } } },
    treasury: { actors: { keeper: { id: 'jiujie-treasury', name: '秤翁', greeting: '功勋与库藏皆有天平。' } } },
    industries: { actors: { construction: { id: 'jiujie-construction', name: '营造监', greeting: '灯楼与长街的修缮均已列入簿册。' }, donation: { id: 'jiujie-donation', name: '捐献使', greeting: '灯油券可助司中修复旧阵。' } } },
    archive: { actors: { keeper: { id: 'jiujie-archive', name: '掌卷', greeting: '档案库只收能经得起灯焰照看的记录。' } } },
    paths: { actors: { guide: { id: 'jiujie-guide', name: '引路吏', greeting: '两道灯法，皆从同一盏灯开始。' } } },
    arena: { actors: { instructor: { id: 'jiujie-instructor', name: '演武教习', greeting: '先照灯，再看对手是否仍要出手。' }, marshal: { id: 'jiujie-marshal', name: '执灯', greeting: '灯台只记行动，不记借口。' } } },
    cultivation: { actors: { keeper: { id: 'jiujie-cultivation', name: '守静', greeting: '闭关之前，先让心神渡过夜声。' } } },
    alchemy: { actors: { keeper: { id: 'jiujie-alchemy', name: '闻香师', greeting: '灯草入炉，火候须听灯声。' } } },
    refinery: { actors: { keeper: { id: 'jiujie-refinery', name: '封灵使', greeting: '旧诡异已经分拣完毕。' } } },
    spiritVein: { actors: { keeper: { id: 'jiujie-vein', name: '灯油监', greeting: '今日灯油井脉没有异常。' }, facility: { id: 'jiujie-pool', name: '灯楼', greeting: '灯楼中央的火光一息未停。' } } },
    herbGarden: { actors: { keeper: { id: 'jiujie-garden', name: '守圃', greeting: '灯下草的枝叶又记下了一夜灯声。' }, facility: { id: 'jiujie-wood', name: '灯下草圃', greeting: '草芽不倒，正好承接余焰。' } } },
    gate: { actors: { keeper: { id: 'jiujie-gatekeeper', name: '守门吏', greeting: '拜帖与来意一致，方可入司。' }, facility: { id: 'jiujie-gate', name: '灯位门', greeting: '长街尽头仍有八盏灯未亮。' } } },
  },
  scenes: { map: { title: '掌灯司舆图', description: '灯楼为心，九灯为界。', loadingText: '正在听取司中灯声……' } },
  terms: { pathChanges: '灯路裁定', meridianPractice: '司中参悟', meridianLoadout: '灯法方案', abilityChanges: '神通裁定', returnToAffairs: '返回司务堂' },
};
